-- SQL Dump generated by export_db.php
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `administradores`;
CREATE TABLE `administradores` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `creado_en` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `administradores` (`id`, `username`, `password_hash`, `creado_en`) VALUES ('1', 'admin', '$2y$10$v9VZU/p1WSwV6NxpsO0VGukZBUxnnZfGOamzYxlIW5ZeZPozhdc.K', '2026-05-12 19:45:48');

DROP TABLE IF EXISTS `estudiantes`;
CREATE TABLE `estudiantes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nombre` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `curso` varchar(50) NOT NULL,
  `fecha_registro` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` enum('Pendiente','Aprobado','Rechazado') DEFAULT 'Pendiente',
  `username` varchar(100) DEFAULT NULL,
  `password_hash` varchar(255) DEFAULT NULL,
  `telefono` varchar(20) DEFAULT NULL,
  `biografia` text,
  `foto_perfil` varchar(255) DEFAULT NULL,
  `calificacion` int DEFAULT NULL,
  `calificacion_algoritmos_geneticos` int DEFAULT NULL,
  `calificacion_machine_learning` int DEFAULT NULL,
  `calificacion_procesamiento_lenguaje` int DEFAULT NULL,
  `certificado_listo` tinyint DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `estudiantes` (`id`, `nombre`, `email`, `curso`, `fecha_registro`, `estado`, `username`, `password_hash`, `telefono`, `biografia`, `foto_perfil`, `calificacion`, `calificacion_algoritmos_geneticos`, `calificacion_machine_learning`, `calificacion_procesamiento_lenguaje`, `certificado_listo`) VALUES ('1', 'Andrus Lopez Franco', 'andruslopez88@gmail.com', 'regresion_lineal', '2026-05-19 12:00:58', 'Aprobado', 'andruslopez88@gmail.com', '$2y$10$.zZ7mBh.97.L2NTuuTFNdel5NG68XGY4MoeQBziA40dL/gZCarN0a', '3118772841', '', 'uploads/perfil_1_1779215696.jpg', NULL, NULL, NULL, NULL, '0');
INSERT INTO `estudiantes` (`id`, `nombre`, `email`, `curso`, `fecha_registro`, `estado`, `username`, `password_hash`, `telefono`, `biografia`, `foto_perfil`, `calificacion`, `calificacion_algoritmos_geneticos`, `calificacion_machine_learning`, `calificacion_procesamiento_lenguaje`, `certificado_listo`) VALUES ('2', 'Jawin Santana garcia', 'auxsistemas.policlinicacienaga@gmail.com', 'algoritmos_geneticos', '2026-05-19 15:20:45', 'Aprobado', 'auxsistemas.policlinicacienaga@gmail.com', '$2y$10$dgS5CeG97T8O6ZstREu1UOjXljzcB.sVl/d5oaSIMQKxIeAkTTXWS', '3007694967', '', 'uploads/perfil_2_1779222504.jpg', NULL, '100', NULL, NULL, '0');

SET FOREIGN_KEY_CHECKS=1;
